# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c630eebe8efcee90d0159dfebf25e37114201f816d71c1fe01cde592edd6eba92602cdf36749fa423c2ce57cd1a0a728c41d49ff4d3238d363aa16d8685ca97

test:
  secret_key_base: 7ffeb4cec415955aa7006d42e77e8f6316065ab99e70afd7620383c848e70e30e7cd23898397e6bb8e4e14e22a6eee197f5b5974564876361968a694e62caf8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
